config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Sidekiq::Web => '/sidekiq'
  root to: 'home#index'

  get 'discover', to: 'discover#index'

  resources :cameras do
    get 'history', to: 'cameras#history'
    get 'history/:video_id', to: 'cameras#play_history', as: :play_video

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/camera.rb
class Camera < ApplicationRecord
  CONNECTION_TYPES = [
    CONNECTION_TYPE_EXTERNAL = 'external',
    CONNECTION_TYPE_INTERNAL = 'internal',
    CONNECTION_TYPE_SIMPLE_PLAY_FROM_URL = 'play_from_url',
  ]

  has_many :videos

  validates :connection_type, presence: true
  validates :name, presence: true
  validates :s3_attribute, uniqueness: true, allow_blank: true
  after_initialize :init

  def self.s3_mapping
    where.not(s3_attribute: nil).pluck(:s3_attribute, :id).to_h
  end

  def init
    if new_record?
      self.token ||= Digest::SHA1.hexdigest "#{Time.now.to_i.to_s}#{feed_url}"
      self.preview_link ||= '/preview/default.png'
      self.connection_type ||= CONNECTION_TYPE_SIMPLE_PLAY_FROM_URL
    end
  end

end

app/models/video.rb
class Video < ApplicationRecord

  default_scope { order(recording_date: :desc) }

  belongs_to :camera
  validates :token, :url_to_video, uniqueness: true
  after_commit :take_thumbnail, on: :create

  after_initialize :init


  def take_thumbnail
    TakePreviewWorker.perform_async id
  end

  def init
    if new_record?
      self.thumbnail_url ||= '/preview/default.png'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cameras_controller.rb
class CamerasController < ApplicationController

  def new
    @resource = Camera.new
  end

  def create
    @resource = Camera.new camera_params
    if @resource.valid?
      @resource.save
      redirect_to @resource
    else
      render action: :new
    end
  end

  def show
    load_camera!
  end

  def history
    load_camera!
    @resources = @resource.videos.page(params[:page] || 1).per_page(10)
  end

  def play_history
    load_camera!
    load_video!
  end

  private

    def load_camera!
      @resource ||= Camera.find(params[:camera_id] || params[:id])
    end

    def load_video!
      @video = Video.find params[:video_id]
    end

    def camera_params
      params.require(:camera).permit(:name, :address, :connection_type, :feed_url, :token, :s3_attribute)
    end

end

app/controllers/discover_controller.rb
class DiscoverController < ApplicationController

  def index
    @resources = Camera.all
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_for name
    params[:action].to_sym == name ? 'active' : ''
  end
end

app/helpers/cameras_helper.rb
module CamerasHelper
end

app/helpers/discover_helper.rb
module DiscoverHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cameras/_shared_header.slim
ruby:
  additional_text ||= ''

.col-lg-12.col-md-12.col-xs-12
  .page-header
    h1
      => resource.name
      small = additional_text.presence || resource.address

app/views/cameras/_shared_nav.slim
ruby:
  play_history ||= false

ul.nav.nav-pills.nav-stacked
  li class="#{active_for(:show)}"
    = link_to camera_path(resource)
      => fa_icon 'play-circle-o'
      | Live
  li class="#{active_for(:history)}"
    = link_to camera_history_path(resource), class: active_for(:history)
      => fa_icon 'history'
      | History
      span.badge = resource.videos.count
  - if play_history
    li class="#{active_for(:play_history)}"
      = link_to '#', class: 'active'
        => fa_icon 'play'
        | Playing history

app/views/cameras/history.slim
= render 'cameras/shared_header', resource: @resource

.row
  .col-lg-3.col-md-5.col-xs-12
    = render 'cameras/shared_nav', resource: @resource

  .col-lg-9.col-md-7.col-xs-12.list-group
    .container-fluid
      - @resources.each do |video|
        .col-lg-3.col-md-4
          .panel.panel-default
            .panel-body.image-cover
              = link_to camera_play_video_path(@resource, video)
                = image_tag video.thumbnail_url
            .panel-footer
              = link_to camera_play_video_path(@resource, video)
                div
                  = video.recording_date.strftime("%d-%m-%y %H:%M")
                div
                  => distance_of_time_in_words_to_now(video.recording_date)
                  | ago
      .col-lg-12.col-md-12.col-xs-12
        = will_paginate @resources, renderer: BootstrapPagination::Rails

app/views/cameras/new.slim
.col-lg-12.col-md-12.col-xs-12
  h2 Add new camera
  hr
= simple_form_for @resource, url: cameras_path do |f|
  = f.input :token, as: :hidden

  .col-lg-6.col-md-6.col-xs-12
    = f.input :name
    = f.input :s3_attribute
    = f.input :feed_url

  .col-lg-12.col-md-12.col-xs-12
    = f.input :connection_type, as: :radio_buttons, collection: Camera::CONNECTION_TYPES.map{ |el| [el, el]}, item_wrapper_class: 'inline'

  .col-lg-12.col-md-6.col-xs-12
    = f.submit 'Create', class: 'btn btn-success'

app/views/cameras/play_history.slim
= render 'cameras/shared_header', resource: @resource, additional_text: "Historical file for #{@video.recording_date.strftime("%e-%m-%y %H:%M")}"

.row
  .col-lg-3.col-md-5.col-xs-12
    = render 'cameras/shared_nav', resource: @resource, play_history: true

  .col-lg-9.col-md-7.col-xs-12.list-group
    .container
      .col-lg-9.col-md-7.col-xs-12
        video#video_block.embed-responsive-item.video-js.vjs-default-skin controls="true" preload="auto" width="640" height="264" poster="#{@video.thumbnail_url}"
          source src="#{@video.url_to_video}" type="video/mp4"

          p.vjs-no-js
            | To view this video please enable JavaScript, and consider upgrading to a web browser that
            a href="http://videojs.com/html5-video-support/" target="_blank"

app/views/cameras/show.slim
= render 'cameras/shared_header', resource: @resource

.row
  .col-lg-3.col-md-5.col-xs-12
    = render 'cameras/shared_nav', resource: @resource

  .col-lg-9.col-md-7.col-xs-12
    .embed-responsive.embed-responsive-16by9 align="center"
      video#video.embed-responsive-item autoplay="true" loop="true" poster="/preview/default.png"

- if @resource.connection_type == Camera::CONNECTION_TYPE_SIMPLE_PLAY_FROM_URL
  - content_for :js
    script src="https://cdn.jsdelivr.net/hls.js/latest/hls.min.js"
    javascript:
      if(Hls.isSupported()) {
        var video = document.getElementById('video');
        var hls = new Hls();
        hls.loadSource("#{@resource.feed_url}");
        hls.attachMedia(video);
        hls.on(Hls.Events.MANIFEST_PARSED,function() {
          video.play();
        });

      } ;

app/views/discover/index.slim
- content_for :js
  script src="https://cdn.jsdelivr.net/hls.js/latest/hls.min.js"

.row
  .col-lg-12.col-md-12.col-xs-12
    .page-header
      h1
        | Discover
        small =< "Total available #{@resources.count} cameras"

  - @resources.find_each do |resource|

    .col-lg-3.col-md-4
      .panel.panel-default
        .panel-heading
          = resource.name
        .panel-body.image-cover
          = link_to camera_path(resource)
            video.embed-responsive-item.index autoplay="true" loop="true" muted="true" id="#{resource.token}" poster=""
        .panel-footer
          .pull-right
            .btn-group
              = link_to camera_path(resource), class: 'btn btn-default'
                => fa_icon 'play-circle-o'
                | Open live
              = link_to camera_path(resource), class: 'btn btn-default dropdown-toggle', data: { togle: 'dropdown' }, aria: { haspopup: true, expanded: false }
                span.caret
                span.sr-only Toggle Dropdown
              ul.dropdown-menu
                li
                  = link_to camera_history_path(resource)
                    => fa_icon 'history'
                    | Open history

          .clearfix

    - content_for :js
      javascript:
        if(Hls.isSupported()) {
          var video = document.getElementById("#{resource.token}");
          var hls = new Hls();
          hls.loadSource("#{resource.feed_url}");
          hls.attachMedia(video);
          hls.on(Hls.Events.MANIFEST_PARSED,function() {
            video.play();
          });
        } ;

app/views/home/index.slim
.row
  .col-lg-12.col-md-12.col-xs-12
  .jumbotron
    h1 Marie
    p Watch your neighborhood with Marie

    = link_to discover_path, class: 'btn btn-lg btn-success'
      => fa_icon 'compass'
      | Browse

app/views/layouts/application.html.slim
doctype html
html
  head
    title Marie demo preview
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    = stylesheet_link_tag    "http://vjs.zencdn.net/5.17.0/video-js.css"
    = stylesheet_link_tag    "application", media: 'all'
    = csrf_meta_tags

  body
    = render 'shared/navbar'
    .container
      = yield

  = javascript_include_tag "application"
  = javascript_include_tag "//vjs.zencdn.net/5.4.6/video.min.js"
  = yield(:js)

app/views/shared/_navbar.slim
= nav_bar fixed: :top, brand: "Marie", responsive: true
  = menu_group
    = menu_item 'Home', root_path
    = menu_divider
    = menu_item discover_path
      => fa_icon 'globe'
      | Discover
    = menu_item new_camera_path
      => fa_icon 'video-camera'
      | Add new
br
br
br